.travis.yml
travis_parse_yaml.py

Used existing script for TravisCI
Modified .travis.yml to add main.yml, site_docker.yml, site_discovery.yml
Testing as follows (with our current errors)
```
 jcallen  ~  Development  kragle  python travis_parse_yaml.py ansible/main.yml ansible/site_discovery.yml ansible/site_docker.yml                   add_travisci 
Running: ansible-playbook --syntax-check ansible/main.yml 
playbook: ansible/main.yml
ERROR: Syntax Error while loading YAML script, /home/jcallen/Development/kragle/ansible/roles/base/tasks/main.yml
Note: The error may actually appear before this position: line 40, column 11
- name: Create SSH Key Pair for root user
user:
^
Running: ansible-playbook --syntax-check ansible/site_discovery.yml 
playbook: ansible/site_discovery.yml
Running: ansible-playbook --syntax-check …
```

Adding TravisCI testing

---

ansible/roles/base/defaults/main.yml
ansible/roles/base/files/iptables
ansible/roles/base/meta/main.yml
ansible/roles/base/tasks/main.yml
ansible/roles/bridge/meta/main.yml

Setting TimeZone using 'defaults'
Starting and enabling ntpd
Opening the firewall for ntpd

Adding NTP service configuration

---

ansible/main.yml
ansible/roles/base/tasks/main.yml

Removed the bridge role from ansible/main.yml
Commented out  '- { name: "wiley", repo: "git://github.com/csc/wiley" }' 
from ansible/roles/basetasks//main.yml
PLAY [Setup kragle] *********************************************************** 
TASK: [base | install updates] ************************************************ 
TASK: [base | install support packages] *************************************** 
changed: [localhost] => (item=ntp,vim,dhcp,wget,docker,python-pip,sshpass,iptables-services,libvirt,libvirt-client,libvirt-python,qemu-img,qemu-kvm,bridge-utils)
TASK: [base | install docker-py] ********************************************** 
TASK: [base | create …

kragle - remove bridge mode

---

ansible/inventory/group_vars/all.yml
ansible/roles/base/tasks/main.yml

```
[root@kragle1 kragle]# ansible-playbook ./ansible/main.yml 
PLAY [Setup kragle] *********************************************************** 
TASK: [base | install updates] ************************************************ 
TASK: [base | install support packages] *************************************** 
ok: [localhost] => (item=ntp,vim,dhcp,wget,docker,python-pip,python-passlib,sshpass,iptables-services,bridge-utils)
TASK: [base | install docker-py] ********************************************** 
TASK: [base | create .ssh directory] ****************************************** 
TASK: [base | Create SSH Key Pair for root user] …
```

Get tagged release

---

ansible/roles/base/tasks/main.yml

This PR adds `ipmitool` to the list of installed support packages.  This tool is used to control power state of nodes and can be scripted.  For instance, the `node_power.sh` script which is part of the wiley project and used for managing the development environment.
The list of packages was alphabetized.
Testing:
```
[root@kragle ansible]# git branch -av
* (detached from mtnbikenc/base-role)     5b1c045 Adding ipmitool to the list of support packages
```
```
[root@kragle ansible]# ansible-playbook main.yml
PLAY [Setup kragle] ***********************************************************
TASK: [base | install updates] ************************************************
TASK: [base | …
```

Adding ipmitool to the list of support packages

---

ansible/inventory/group_vars/all.yml
ansible/main.yml
ansible/roles/base/tasks/main.yml
ansible/roles/createrepo/tasks/main.yml
ansible/roles/createrepo/templates/repo_template.repo.j2

Started at the end of base role so not. 
[root@kragle2 ansible]# ansible-playbook main.yml --start-at-task="clone repos from git" -vv --step
PLAY [Setup kragle] ***********************************************************
<localhost> REMOTE_MODULE setup
Perform task: base | clone repos from git (y/n/c): n
Perform task: createrepo | create repo directory for httpd (y/n/c): y
Perform task: createrepo | create repo directory for httpd (y/n/c):  **********
<localhost> REMOTE_MODULE file state=directory path=/var/www/html/kragle-offline
ok: [localhost] => {"changed": false, "gid": 0, "group": "root", "mode": "0755", "owner": "root", "path": "/var/www/html/kragle-offline", "secontext": …

Repo create

---

ansible/inventory/group_vars/all.yml

Changed the offline rpm vars 
Grouped all offline vars together
[root@nuc ansible]# ansible-playbook main.yml 
PLAY [Setup kragle] *********************************************************** 
TASK: [base | install updates] ************************************************ 
TASK: [base | install support packages] *************************************** 
ok: [localhost] => (item=bridge-utils,dhcp,docker,ipmitool,iptables-services,ntp,python-passlib,python-pip,sshpass,vim,wget,httpd,createrepo,yum-utils)
TASK: [base | install docker-py] ********************************************** 
TASK: [base | install docker-py when offline] …

kragle - offline vars

---

ansible/site_docker.yml

Changed the shell to command in site_docker.yml
[root@nuc ansible]# ansible-playbook site_docker.yml 
PLAY [Start Hanlon Docker Environment] **************************************** 
TASK: [Clean up existing containers] ****************************************** 
ok: [localhost] => (item={'image': 'mongo', 'name': 'hanlon-mongo'})
ok: [localhost] => (item={'image': 'cscdock/hanlon', 'name': 'hanlon-server'})
ok: [localhost] => (item={'image': 'cscdock/atftpd', 'name': 'hanlon-atftpd'})
TASK: [Load Mongo, Hanlon and Atftpd Containers Offline] ********************** 
changed: [localhost] => (item=mongo.tar)
changed: [localhost] => (item=cscdock_hanlon.tar)
changed: [localhost] => …

kragle - changed shell to command

---

ansible/inventory/group_vars/all.yml
ansible/roles/base/tasks/main.yml

Format change when: indention
Syntax added / to end of path
[root@nuc ansible]# ansible-playbook main.yml
PLAY [Setup kragle] *********************************************************** 
TASK: [base | install updates] ************************************************ 
TASK: [base | install support packages] *************************************** 
ok: [localhost] => (item=bridge-utils,dhcp,docker,ipmitool,iptables-services,ntp,python-passlib,python-pip,sshpass,vim,wget,httpd,createrepo,yum-utils)
TASK: [base | install docker-py] ********************************************** 
TASK: [base | install docker-py when offline] ********************************* …

kragle - syntax changes

---

ansible/library/hanlon_active_model.py
ansible/library/hanlon_image.py
ansible/library/hanlon_model.py
ansible/library/hanlon_policy.py

https://github.com/csc/wiley/pull/93
https://github.com/csc/wiley/pull/92
https://github.com/csc/wiley/pull/79
https://github.com/csc/wiley/pull/74

Hanlon Modules updated from Wiley project

---

ansible/files/final-rpm-list.txt
ansible/initial_stage.yml
ansible/inventory/group_vars/all.yml
ansible/library/selenium.py
ansible/roles/base/tasks/main.yml
ansible/roles/base/vars/main.yml
ansible/site_discovery.yml
ansible/stage_usb.yml

The initial_stage.yml will create the directory tree on the usb drive and download the latest tagged version of the public git repos
The stage_usb.yml will be run from the usb drive Kragle and will go out and download all other resources to the usb drive
```
[root@stage-node ~]# ansible-playbook initial_stage.yml
PLAY [Download the Kragle source repo] ****************************************
TASK: [Create the staging directories on the usb hard drive] ******************
ok: [localhost] => (item=/mnt/sdb/autodeploy/projects)
ok: [localhost] => (item=/mnt/sdb/autodeploy/resources)
TASK: [Determine the latest tagged versions of public source Git repos] *******
ok: [localhost] => (item={'repo': 'git://github.com/csc/kragle', 'tag': 'https://api.github.com/repos/csc/kragle/tags', 'name': …
```

Staging - changes for the staging node

---

ansible/inventory/group_vars/all.yml
ansible/stage_usb.yml

Had to change a variable kragle_ to autodeploy_

kragle - fixed changed variable

---

ansible/inventory/group_vars/all.yml
ansible/roles/prep-projects/tasks/scaleio.yml
ansible/roles/prep-projects/tasks/wiley.yml
ansible/roles/prep-projects/vars/main.yml
ansible/stage_resources.yml

Added checks to stage_resources for downloading private git
Added tar for private git project
Added vars to group_vars/all.yml

Kragle - Changes to prep-projects

---

ansible/inventory/group_vars/all.yml
ansible/roles/createrepo/tasks/main.yml
ansible/roles/createrepo/templates/offline.repo.j2

Made the default offline repo for http
/var/www/html/repo
```
TASK: [createrepo | create repo directory for httpd] **************************
TASK: [createrepo | copy repo files to http directory] ************************
TASK: [createrepo | createrepo] ***********************************************
TASK: [createrepo | repofile to provide to node] ******************************
TASK: [createrepo | start httpd] **********************************************
```

kragle - changes to createrepo role

---

ansible/files/rhn_rpm_packages.txt

Several packages required by ScaleIO are being added to the RHN RPM list.

Adding required ScaleIO packages

---

ansible/main.yml

Included the site_docker and site_discovery yaml files.

kragle - include other .yml

---

ansible/inventory/group_vars/all.yml

Updating private repo to current tagged release.

Bumping private repo version

---

ansible/library/selenium.py

In Ansible 2.0 `exit_json` and `fail_json` contains a method `remove_values`
that does not like random objects in the dictionary `params`.
Before executing those methods this PR removes the `driver` item from the dictionary.
Testing...
```
[root@ansible20 ansible]# ansible-playbook -vvvv -t selenium /opt/autodeploy/projects/kragle/ansible/stage_resources.yml -i /opt/autodeploy/projects/kragle/ansible/inventory/hosts.ini
Using /opt/autodeploy/projects/kragle/ansible/ansible.cfg as config file
Loaded callback default of type stdout, v2.0
1 plays in /opt/autodeploy/projects/kragle/ansible/stage_resources.yml
PLAY [Stage DCAF automation resources on autodeploynode] ***********************
TASK [setup] *******************************************************************
ESTABLISH LOCAL …
```

Modifications to selenium module for Ansible 2.0

---

ansible/library/hanlon_active_model.py
ansible/library/hanlon_image.py
ansible/library/hanlon_model.py
ansible/library/hanlon_node.py
ansible/library/hanlon_policy.py

This PR will assist in kragle running under Ansible 2.0.
See https://github.com/csc/wiley/pull/107 for details.

Updating Hanlon modules from Wiley Project

---

ansible/initial_stage.yml
ansible/roles/base/tasks/main.yml
ansible/roles/prep-projects/tasks/scaleio.yml
ansible/stage_resources.yml

Simple updates to remove bare variable format to align with Ansible 2.0
Testing:
```
2016-02-05 08:57:00,443 p=24278 u=root |  PLAY RECAP *********************************************************************
2016-02-05 08:57:00,444 p=24278 u=root |  localhost                  : ok=51   changed=26   unreachable=0    failed=0
```

Minor updates for running with Ansible 2.0

---

ansible/files/pip-requirements.txt
ansible/inventory/group_vars/all.yml

Adding pyvmomi 5.5.  Adding openssl-devel and glibc.i686 to
support executing esxcli.

Add prereq to Kragle to support Emmet

---

ansible/initial_stage.yml
ansible/inventory/group_vars/all.yml
ansible/roles/base/tasks/main.yml
ansible/stage_resources.yml

This PR modifies the way git repos are cloned so that a username/password is not required, however a key file must be specified.  This change simplifies the way deployments can be performed by not requiring a user's GitHub password to be handed out.
The key file can be created like this:
```
cat << EOF > ~/github.pem
-----BEGIN RSA PRIVATE KEY-----
<insert_key_file_text_here>
-----END RSA PRIVATE KEY-----
EOF
chmod 0600 ~/github.pem
```
The key file location can then be specified using `extra-vars` at the command line.
initial_stage.yml testing:
```
[root@rhel72 ~]# ansible-playbook initial_stage.yml --extra-vars "github_key_file=~/github.pem"
[WARNING]: provided hosts list is empty, only localhost is available
PLAY [Download the Kragle source repo] …
```

Changes to git clone process to use ssh key

---

ansible/roles/createrepo/README.md

Documenting the createrepo role.
No testing required.

abe - document createrepo

---

ansible/build.sh

Tested online and offline builds with source built RPM.
```
ONLINE INSTALL 
==============
Installed:
ansible.noarch 0:2.0.1.0-0.git201602242329.bb6cade.HEAD.el7
Dependency Installed:
PyYAML.x86_64 0:3.10-11.el7                    libtomcrypt.x86_64 0:1.17-23.el7                libtommath.x86_64 0:0.42.0-4.el7
libyaml.x86_64 0:0.1.4-11.el7_0                python-babel.noarch 0:1.3-6.el7ost              python-ecdsa.noarch 0:0.11-3.el7ost
python-httplib2.noarch 0:0.7.7-3.el7ost        python-jinja2.noarch 0:2.7.2-2.el7              python-keyczar.noarch 0:0.71c-2.el7
python-markupsafe.x86_64 0:0.11-10.el7         python-paramiko.noarch 0:1.15.1-1.el7ost        python-pyasn1.noarch 0:0.1.6-2.el7
python-six.noarch 0:1.9.0-2.el7                python2-crypto.x86_64 0:2.6.1-9.el7 …
```

Bumping Ansible to 2.0.1.0 stable

---

docsite/source/conf.py
docsite/source/index.rst
docsite/source/overview.rst
docsite/source/requirements.rst

Adding overview and requirements docs

---

docsite/Makefile

Need to chain all the commands together in order for them to be processed in the same shell context.

Updating syntax in Makefile

---

docsite/source/index.rst
docsite/source/quickstart.rst

This only covers through ABE. 
Will submit another PR for other projects as add to this.

abe quickstart

---

docsite/source/quickstart.rst

quickstart- syntax

---

docsite/source/index.rst
docsite/source/known_issues.rst

Convert known-issues.
The stonith was omitted because it is disabled by default

issues - known issues
