kickstart-files/ks-atomic.cfg
kickstart-files/ks-isolinux-packer.cfg
kickstart-files/ks-isolinux.cfg
kickstart-files/ks-uefi.cfg
patch-files/iso-mods.patch

This PR fixes issues associated with kickstart and patch files during recent work to add ansible playbook runs to the kickstart files used when performing an unattended install of RHEL 7.1 from a thumb drive

Fixes issues associated with kickstart and patch files

---

ansible/inventory/group_vars/all.yml
ansible/library/hanlon_active_model.py
ansible/library/hanlon_image.py
ansible/library/hanlon_model.py
ansible/library/hanlon_node.py
ansible/library/hanlon_policy.py
ansible/roles/base/tasks/main.yml
ansible/roles/dhcp-server/handlers/main.yml
ansible/roles/dhcp-server/tasks/main.yml
ansible/roles/dhcp-server/templates/dhcpd.conf.j2
ansible/site_discovery.yml
ansible/site_docker.yml

These were all kragle related items that were in wiley
- site_discovery group_vars
- hanlon modules
- dhcp server role
- site_docker.yml
- site_discovery.yml
RESULTS:
ansible-playbook ./ansible/site_docker.ymlPLAY [Start Hanlon Docker Environment] 
TASK: [Ansible Docker Requirements] ******************************************* 
changed: [localhost] => (item=six==1.4.1)
changed: [localhost] => (item=docker-py==1.1.0)
changed: [localhost] => (item=requests==2.7.0)
TASK: [Clean up existing containers] ****************************************** 
changed: [localhost] => (item={'image': 'mongo', 'name': 'hanlon-mongo'})
changed: [localhost] => (item={'image': 'cscdock/hanlon', 'name': …

kragle - moving things out of wiley

---

ansible/roles/base/tasks/main.yml
ansible/roles/dhcp-server/tasks/main.yml

The task for copying the ssh/config file was improperly setting the file mode once it was copied.  This is noted in the ansible copy module docs that the mode is octal and leaving off the leading '0' can have unexpected results.
http://docs.ansible.com/ansible/copy_module.html
Current behavior (see "mode": "01130"):
```bash
TASK: [base | copy .ssh/config] ***********************************************
ok: [localhost] => {"changed": false, "checksum": "d2affc93ee309978d9bb9f9367d84e591c27124a", "dest": "/root/.ssh/config", "gid": 0, "group": "root", "mode": "01130", "owner": "root", "path": "/root/.ssh/config", "secontext": "system_u:object_r:ssh_home_t:s0", "size": 86, "state": "file", "uid": 0}
```
Corrected behavior:
```bash
TASK: [base | copy .ssh/config] …
```

Correcting file mode for ssh/config

---

ansible/roles/base/tasks/main.yml

The pub key for the deployment node is not in the ssh authorized users.  This causes some tasks in other projects to fail when trying to connect to the deployment node.  This PR adds the key.
Testing:
```bash
TASK: [base | Retrieve deployment node public key] ****************************
TASK: [base | Add deployment node SSH key to node authorized users] ***********
```

Adding tasks to add pub key to auth users

---

ansible/site_docker.yml

These changes are to support running kragle in an offline mode.
The site_docker.yml would update some pip dependencies required for the
docker module to function properly. These dependencies are no longer
required and have been removed.
Additionally, the docker module tasks have been updated to pull only when
the required docker image is missing, preventing the system from trying
to update the image every time.  With these changes, the site_docker.yml
playbook can be run while kragle is 'offline'.
site_docker.yml Offline Testing:
```
[root@localhost kragle]# ansible-playbook ./ansible/site_docker.yml
PLAY [Start Hanlon Docker Environment] ****************************************
TASK: [Clean up …
```

Updating Docker configuration for Ansible

---

ansible/inventory/group_vars/all.yml
ansible/roles/base/tasks/main.yml
ansible/site_discovery.yml
ansible/site_docker.yml

Added to copy the Hanlon microkernel when offline
[root@nuc ansible]# ansible-playbook site_discovery.yml 
PLAY [Configure deployment node for site discovery] *************************** 
TASK: [dhcp-server | install dhcp server package] ***************************** 
TASK: [dhcp-server | setup dhcpd.conf] **************************************** 
TASK: [dhcp-server | enable dhcpd service] ************************************ 
TASK: [Check for local copy of Hanlon Microkernel] **************************** 
TASK: [Download Hanlon Microkernel] ******************************************* 
TASK: [Copy Hanlon …

Kragle - Site_discovery

---

docs/ansible_offline.md

Added documentation that will allow us to execute Ansible playbooks without installing Ansible via a distro-package or python pip.

Ansible offline documentation

---

ansible/roles/dhcp-server/defaults/main.yml
ansible/roles/dhcp-server/files/ipxe-option-space.conf
ansible/roles/dhcp-server/tasks/main.yml
ansible/roles/dhcp-server/templates/dhcpd.conf.j2
ansible/roles/dhcp-server/templates/ipxe.conf.j2

Used `packer: true` because my home lab does not have the same subnet as Austin lab.  Will add further testing.
```
➜  ansible git:(06dfcc1) ✗ ansible-playbook -e '{"packer": true}' site_discovery.yml
PLAY [Configure deployment node for site discovery] ***************************
TASK: [dhcp-server | install dhcp server package] *****************************
TASK: [dhcp-server | Configure dhcpd.conf] ************************************
TASK: [dhcp-server | Configure ipxe.conf] *************************************
TASK: [dhcp-server | Copy ipxe-option-space.conf] *****************************
TASK: [dhcp-server | enable dhcpd …
```

Ipxe changes

---

ansible/files/epel_rpm_packages.txt
ansible/files/rhn_rpm_packages.txt
ansible/inventory/group_vars/all.yml
ansible/stage_resources.yml

There are conflicting package versions between EPEL and RHN repos where packages from RHN are required.  These changes split the download of packages to ensure the correct versions are downloaded.
The required version of mongodb from RHN is: mongodb-2.6.5-2.el7ost.x86_64
Testing:
```
[root@staging ansible]# ansible-playbook -v stage_resources.yml --tags=pkgs,repo
...
PLAY RECAP ********************************************************************
localhost                  : ok=6    changed=3    unreachable=0    failed=0
```
Confirming the right version of mongo was downloaded:
```
[root@staging ansible]# ls -l /opt/autodeploy/resources/rpms/mong*
-rw-r--r--. 1 root root 59699728 Jan 19  2015 /opt/autodeploy/resources/rpms/mongodb-2.6.5-2.el7ost.x86_64.rpm
-rw-r--r--. 1 root root  9130984 …
```

Separarting EPEL packages from RHN packages

---

ansible/files/rhn_rpm_packages.txt
ansible/inventory/group_vars/all.yml

python-netaddr is required in place of python-ipaddr.  The package has
been added to the RHN package list as well as the required support
packages for the autodeploy node.  This library is required for the
slimer demo role jinja2 filters which are run on the autodeploynode.

Adding python-netaddr

---

ansible/roles/base/tasks/main.yml

Fixed issue where 
```
TASK: [Start Hanlon Server Container] *****************************************
failed: [localhost] => {"changed": true, "failed": true}
msg: Docker API Error: Cannot start container 53077093e449856e519e39932238ae28bc5c9c4a3ee783e72689e4df8dd9e2e8: iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 8026 -j DNAT --to-destination 172.17.0.2:8026 ! -i docker0: iptables: No chain/target/match by that name.
(exit status 1)
```
now:
```
TASK: [Start Hanlon Server Container] *****************************************
```

Fixed logic error in base role in kragle.

---

.travis.yml
ansible/files/pip-requirements.txt
ansible/files/rhn_rpm_packages.txt
ansible/inventory/group_vars/all.yml
ansible/roles/base/tasks/main.yml
ansible/roles/createrepo/tasks/main.yml
ansible/roles/prep-projects/tasks/scaleio.yml
ansible/site_discovery.yml
ansible/site_docker.yml
ansible/stage_resources.yml

With recent changes in upstream docker RPM packages as well as docker-py python modules, several dependencies have broken Ansible functionality. These changes pin docker to version 1.7.1 and docker-py to 1.4 for functionality with Ansible 1.9.4.
Testing was performed in virtual machines on my local laptop.
Testing (Offline):
Staging Node (10.0.10.5)
```
subscription-manager register --username='xxxx'  --password='xxxx'
subscription-manager attach --pool=xxxx
subscription-manager repos --disable=*
subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-optional-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-openstack-6.0-rpms --enable=rhel-server-rhscl-7-rpms --enable=rhel-ha-for-rhel-7-server-rpms
yum -y install …
```

Updates for pinning docker package versions

---

ansible/inventory/group_vars/all.yml
ansible/stage_resources.yml

Made Kragle idempotent except for the rpms where we are using repotrack. Need to find 'better' way to handle that?
```
[root@staging ansible]# ansible-playbook stage_resources.yml
PLAY [Prepare the staging resources] ******************************************
TASK: [Install required support packages] *************************************
ok: [localhost] => (item=createrepo,dhcp,docker-1.7.1,firefox,genisoimage,httpd,ipmitool,iptables-services,ntp,python-netaddr,python-passlib,python-pip,python-xvfbwrapper,sshpass,unzip,vim,wget,xorg-x11-server-Xvfb,yum-utils)
TASK: [Install required pip-based support packages] ***************************
TASK: [Create the staging directories in …
```

kragle - idempotence

---

ansible/stage_resources.yml

```
[root@autodeploy72 ansible]# ansible-playbook stage_resources.yml --tags=git
PLAY [Stage DCAF automation resources on autodeploynode] **********************
TASK: [Check if private project tar.gz exists in /opt/autodeploy/projects] ****
TASK: [Download the private project repo from Git to /opt/autodeploy/projects] ***
TASK: [Check if private project was extracted in /opt/autodeploy/projects] ****
TASK: [Extract the private project source files] ******************************
```

Bug fix for private repo extraction

---

ansible/inventory/group_vars/all.yml
ansible/site_docker.yml

With the microkernel changes to Hanlon we need to specify
the specific version of the container we want to run until we
can update the Ansible modules and test the new microkernel.
Testing will follow.

Added build version specific value for Hanlon Docker container

---

ansible/inventory/group_vars/all.yml

```
[root@autodeploy72 ansible]# ansible-playbook stage_resources.yml --tags=iso
PLAY [Stage DCAF automation resources on autodeploynode] **********************
TASK: [Check if Hanlon Microkernel file exists in /opt/autodeploy/resources/ISO] ***
---
TASK: [Download the Hanlon microkernel image to /opt/autodeploy/resources/ISO] ***
TASK: [Check if RHEL DVD ISO file exists in /opt/autodeploy/resources/ISO] ****
TASK: [Find the RHEL DVD ISO file url] ****************************************
TASK: [Download the RHEL DVD ISO file to /opt/autodeploy/resources/ISO] *******
TASK: [Check if Red Hat KVM Guest image …
```

Moving downloaded resources to RHEL 7.2

---

ansible/roles/base/tasks/main.yml

This PR updates the default Ansible config file to include the standard changes made for project related inventories.  Having an ansible.cfg file in each inventory location will no longer be required.  This change is in preparation for moving inventory management to a separate project.
```
TASK: [base | Update default Ansible configuration] ***************************
changed: [localhost] => (item={'regexp': 'inventory', 'line': 'inventory = ./hosts.ini'})
changed: [localhost] => (item={'regexp': 'forks', 'line': 'forks = 20'})
changed: [localhost] => (item={'regexp': 'host_key_checking', 'line': 'host_key_checking = False'})
changed: [localhost] => (item={'regexp': 'log_path', 'line': 'log_path = ./ansible.log'})
changed: [localhost] => (item={'regexp': 'ssh_args', 'line': 'ssh_args = -o …
```

Configure the global Ansible config file

---

ansible/stage_resources.yml

This PR corrects the checking of the private repo extraction so the archive is only extracted if the `roles` directory does not exist.  I chose `roles` because it seemed like a directory which would always exist for the project.  A folder inside the archive needed to be tested.  The Ansible `unarchive` module was investigated, but the extracted files were placed in a sub-directory named the same as the archive.  PRs to Ansible exist to enable passing addtional `tar` options but are not yet merged so using the module is not yet practical.
Testing:
```
[root@autodeploynode ansible]# ansible-playbook stage_resources.yml --tags=git
PLAY [Stage DCAF automation resources on autodeploynode] **********************
ok: …
```

Correcting git archive extract idempotence

---

ansible/inventory/group_vars/all.yml
ansible/roles/dhcp-server/defaults/main.yml
ansible/roles/dhcp-server/templates/dhcpd.conf.j2
ansible/roles/dhcp-server/vars/main.yml
ansible/site_discovery.yml

This PR cleans up the user required variables for a successful build.
The `auto_deploy_node` variable was replaced with `ansible_default_ipv4.address`
The `hanlon_base_url` was moved to the site_discovery.yml playbook where it is used.
The DHCP configuration variables have been moved to the dhcp-server role, with the user definable vars put in `defaults/main.yml` and the project vars put in `vars/main.yml`.  Sane defaults for testing have been configured.
Testing:
```
[root@rhel72 ansible]# ansible-playbook main.yml
PLAY [Stage DCAF automation resources on autodeploynode] **********************
TASK: [base | Install required support packages] ******************************
ok: [localhost] => …
```

Simplifying variables

---

ansible/roles/verify-files/tasks/main.yml
ansible/site_docker.yml

Bare variables are no longer allowed for `with_items` task attributes.  While correcting this syntax, a bug was discovered which was introduced In November when some variable changes were made and the `docker_files` dictionary was replaced by `docker_images`.  This bug has also been corrected.  The `verify_files` role is not currently in use, however the code in this role has been updated.
Testing (online):
```
TASK [Load Mongo, Hanlon and Atftpd Containers (Offline)] **********************
skipping: [localhost] => (item={u'tar_file': u'mongo.tar', u'image': u'mongo', u'name': u'hanlon-mongo'})
skipping: [localhost] => (item={u'tar_file': u'cscdock_hanlon.tar', u'image': u'cscdock/hanlon:2.5.0', u'name': u'hanlon-server'})
skipping: [localhost] => (item={u'tar_file': …
```

Syntax updates for Ansible 2.0

---

ansible/roles/createrepo/tasks/main.yml
ansible/roles/createrepo/templates/offline_repo.conf

Changed the createrepo role so that the offline repo created by stage_resources can be used by other projects.
```
PLAY [Test for Kragle] ********************************************************
TASK: [Create offline repo file to provide to hosts] **************************
TASK: [Create repo file to provide to hosts] **********************************
TASK: [Start the httpd service] ***********************************************
PLAY RECAP ********************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=0
```

kragle - create repo mods

---

ansible/init.sh

This script will perform the necessary steps to deploy a kragle build.
Ansible 2.0 is cloned and an RPM is built to install a current version.
Testing was performed by walking through the test for PR #71.
NOTE: This PR requires PR #71.

Adding installation script to support Ansible 2.0

---

ansible/roles/base/tasks/main.yml
ansible/roles/prep-projects/tasks/scaleio.yml
ansible/roles/prep-projects/vars/main.yml
ansible/stage_resources.yml

This PR fixes some bugs in the scaleio section of the prep-projects role.
Variables were specified in two locations and one of them was incorrect.  With changes in Ansible versions the variable precedence changed and started picking up the incorrect variable.  Additionally, a task conditional was not running correctly if the file didn't exist and therefore caused another task failure because the downloaded zip file was not being extracted.
Error:
```
TASK [prep-projects : Download ScaleIO files for ansible-scaleio project (Online)] ***
fatal: [localhost]: FAILED! => {"changed": false, "dest": "/opt/autodeploy/resources/scaleio/", "failed": true, "gid": 0, "group": "root", "mode": "0755", "msg": "Request failed", "owner": "root", "response": "HTTP Error 404: Not Found", "secontext": …
```

Fix bugs for scaleio prep-projects

---

ansible/build.sh

Ansible branch stable-2.0 is not stable.  They are committing small changes which makes working code fail.   A tagged release is much more stable in the sense it is not a moving target and gives us the stability we need to be able to develop and test our code.  This PR updates the build script to use a tagged release (v2.0.1.0-0.1.rc1).
Note: The script was renamed from init.sh to build.sh to more accurately reflect it's function.
Testing (after Ansible RPM build):
```
Installed:
ansible.noarch 0:2.0.1.0-0.git201601282137.870a4b8.HEAD.el7
Dependency Installed:
PyYAML.x86_64 0:3.10-11.el7               libtomcrypt.x86_64 0:1.17-23.el7           libtommath.x86_64 0:0.42.0-4.el7
libyaml.x86_64 0:0.1.4-11.el7_0           python-babel.noarch 0:1.3-6.el7ost         python-ecdsa.noarch …
```

Updating Ansible RPM build to use tagged release

---

ansible/site_docker.yml

Remove commented out Cassandra referenes.
We had planned on possibly moving to Cassandra but that fell through so for now to clean up 
dcaf-abe removing it and can re-add if and when we go to Cassandra.

abe - remove cassandra reference

---

ansible/stage_resources.yml

This PR is for temporary changes to the stage_resources.yml needed until Ansible 2.x is included in epel. It does the following:
1. Find the name of the Ansible RPM built by deploy script
2. Download any new dependencies for this RPM if any, if there aren't any repotrack errors with a warning that we ignore
3. Copy the Ansible RPM to the /opt/autodeploy/resources/rpms directory
```
PLAY [Stage DCAF automation resources on autodeploynode] ***********************
TASK [setup] *******************************************************************
TASK [Download the EPEL RPMs to /opt/autodeploy/resources/rpms when offline] ***
TASK [Download the Red Hat RPMs to /opt/autodeploy/resources/rpms when offline]
TASK [Determine name of custom …
```

abe - ansible rpm in repo

---

ansible/roles/base/tasks/main.yml
ansible/stage_resources.yml

Resolves an issue if plays were not ran out of the `/opt/autodeploy/projects` directory.
```bash 
⚡ root@piptest1  /opt/autodeploy/projects/dcaf-abe/ansible  ➦ 856fff2  ansible-playbook stage_resources.yml --extra-vars "github_key_file=~/github.pem rhn_user=$RHN_USER rhn_pass=$RHN_PASS"
PLAY [Stage DCAF automation resources on autodeploynode] ***********************
TASK [setup] *******************************************************************
TASK [Install required support packages] ***************************************
changed: [localhost] => (item=[u'createrepo', u'dhcp', u'docker-1.7.1', u'firefox', u'genisoimage', u'httpd', u'ipmitool', u'iptables-services', u'ntp', u'python-netaddr', u'python-passlib', u'python-pip', u'python-xvfbwrapper', u'sshpass', …
```

Changes pip install to use relative paths

---

ansible/inventory/group_vars/all.yml

Updated as per changes on 2/24/2016 at https://access.redhat.com/downloads/content/69/ver=/rhel---7/7.2/x86_64/product-software

Updating RHEL KVM guest image filename

---

.travis.yml
ansible/files/pip-requirements.txt
ansible/files/rhn_rpm_packages.txt
ansible/inventory/group_vars/all.yml
ansible/site_docker.yml
ansible/stage_resources.yml

With the move to Ansible v2, the project is no longer limited by support of a specific version of docker.  This pull request updates the project to use the latest version of docker and docker-py.  The Docker API version still needs to be set to a specific version due to the fact that the default Docker API version set in docker-py is higher than the version available for the docker package.
* docker.x86_64    1.8.2-10.el7      rhel-7-server-extras-rpms => Docker 1.8.x API version = 1.20
* docker-py 1.7.1 => default Docker API version = 1.21 (Docker 1.9.x)
Additionally, the `docker_api_version` variable must be quoted or `1.20` will be transformed to `1.2`, and will not function properly.
Due to the version change of docker-py, the check for pip dependencies has been updated to no longer …

Changes for docker version update

---

ansible/stage_resources.yml

A bug was discovered in the task where the RPM dependencies for the self-created Ansible RPM are downloaded.  `repotrack` does not support specifying an RPM.
Testing:
```
TASK [Find Ansible RPM dependencies] *******************************************
changed: [localhost] => (item=/root/ansible/rpm-build/ansible-2.0.1.0-0.git201602242329.bb6cade.HEAD.el7.noarch.rpm)
TASK [Download the Ansible dependent RPMs when offline] ************************
changed: [localhost] => (item=python-httplib2.noarch)
changed: [localhost] => (item=python-jinja2.noarch)
changed: [localhost] => (item=python-keyczar.noarch)
changed: [localhost] => (item=python-paramiko.noarch)
changed: [localhost] => (item=python-setuptools.noarch)
changed: [localhost] => (item=python-six.noarch)
changed: [localhost] => …
```

Updating method to download Ansible dependencies
